module.exports = {
    folder_app:'my-app/',
    folder_configs:'configs/',
    folder_routes_backend:'routes/backend/',
    folder_routes_frontend:'routes/frontend/',
    folder_views:'views/',
    folder_views_backend:'views/backend',
    folder_views_frontend:'views/frontend',
    folder_helpers:'helpers/',
    folder_shemas:'shemas/',
    folder_uploads:'uploads/',
    folder_middleware:'middleware/',
    folder_models:'models/',
    folder_public:'public/',
}